export class Phrase {
  constructor(public nadsat: Array<String>, public english: Array<string>) {}
}

export const phrases = [
  new Phrase(['Appypolly loggy'], ['Apology']),
  new Phrase(['Baboochka'], ['Old woman']),
  new Phrase(['Baddiwad'], ['Bad']),
  new Phrase(['Banda'], ['Band']),
  new Phrase(['Bezoomy'], ['Mad']),
  new Phrase(['Biblio'], ['Library']),
  new Phrase(['Bitva'], ['Battle']),
  new Phrase(['Bog'], ['God']),
  new Phrase(['Bolnoy'], ['Sick']),
  new Phrase(['Bolshy'], ['Big']),
  new Phrase(['Bratchny'], ['Bastard']),
  new Phrase(['Bratty'], ['Brother']),
  new Phrase(['Britva'], ['Razor']),
  new Phrase(['Brooko'], ['Belly']),
  new Phrase(['Brosay'], ['Throw']),
  new Phrase(['Bugatty'], ['Rich']),
  new Phrase(['Cal'], ['Shit']),
  new Phrase(['Cancer'], ['Cigarette']),
  new Phrase(['Cantora'], ['Office']),
  new Phrase(['Carman'], ['Pocket']),
  new Phrase(['Chai'], ['Tea']),
  new Phrase(['Charlie'], ['Chaplain', 'Priest']),
  new Phrase(['Chasha'], ['Cup']),
  new Phrase(['Chasso'], ['Guard']),
  new Phrase(['Cheena'], ['Woman']),
  new Phrase(['Cheest'], ['Wash']),
  new Phrase(['Chelloveck'], ['Fellow']),
  new Phrase(['Chepooka'], ['Nonsense']),
  new Phrase(['Choodessny'], ['Wonderful']),
  new Phrase(['Chumble'], ['Mumble']),
  new Phrase(['Clop'], ['Knock']),
  new Phrase(['Cluve'], ['Beak']),
  new Phrase(['Collocol'], ['Bell']),
  new Phrase(['Crark'], ['Yowl']),
  new Phrase(['Crast'], ['Steal']),
  new Phrase(['Creech'], ['Scream']),
  new Phrase(['Cutter'], ['Money']),
  new Phrase(['Dama'], ['Lady']),
  new Phrase(['Ded'], ['Old Man']),
  new Phrase(['Deng'], ['Money']),
  new Phrase(['Devotchka'], ['Girl']),
  new Phrase(['Dobby'], ['Good']),
  new Phrase(['Domy'], ['House']),
  new Phrase(['Dook'], ['Ghost']),
  new Phrase(['Dorogoy'], ['Valuable']),
  new Phrase(['Drat'], ['Fight']),
  new Phrase(['Drencrom'], ['A drug']),
  new Phrase(['Droog'], ['Friend']),
  new Phrase(['Dva'], ['Two']),
  new Phrase(['Eegra'], ['Game']),
  new Phrase(['Eemya'], ['Name']),
  new Phrase(['Eggiweg'], ['Egg']),
  new Phrase(['Em'], ['Mum']),
  new Phrase(['Fagged'], ['Tired']),
  new Phrase(['Filly'], ['Play']),
  new Phrase(['Firegold'], ['A particular drink']),
  new Phrase(['Forella'], ['Trout']),
  new Phrase(['Gazetta'], ['Newspaper']),
  new Phrase(['Glazz'], ['Eye']),
  new Phrase(['Gloopy'], ['Stupid']),
  new Phrase(['Godman'], ['Priest']),
  new Phrase(['Golly'], ['Unit of Money']),
  new Phrase(['Goloss'], ['Voice']),
  new Phrase(['Goober'], ['Lip']),
  new Phrase(['Gooly'], ['To Walk']),
  new Phrase(['Gorlo'], ['Throat']),
  new Phrase(['Govoreet'], ['To speak or talk']),
  new Phrase(['Grazhny'], ['Dirty']),
  new Phrase(['Grazzy'], ['Soiled']),
  new Phrase(['Gromky'], ['Loud']),
  new Phrase(['Groody'], ['Breast']),
  new Phrase(['Gruppa'], ['Group']),
  new Phrase(['Guff'], ['Laugh']),
  new Phrase(['Gulliver'], ['Head']),
  new Phrase(['Guttiwuts'], ['Guts']),
  new Phrase(['Hen-korm'], ['Chickenfeed']),
  new Phrase(['Horn'], ['To Cry Out']),
  new Phrase(['Horrorshow'], ['Good', 'well']),
  new Phrase(['Hound-and-Horny'], ['corny']),
  new Phrase(['In-out-in-out'], ['Sex']),
  new Phrase(['Interessovat'], ['To interest']),
  new Phrase(['Itty'], ['To go']),
  new Phrase(['Jammiwam'], ['Jam']),
  new Phrase(['Jeezny'], ['Life']),
  new Phrase(['Kartoffel'], ['Potatoes']),
  new Phrase(['Keeshkas'], ['Guts']),
  new Phrase(['Kleb'], ['Bread']),
  new Phrase(['Klootch'], ['Key']),
  new Phrase(['Knopka'], ['Button']),
  new Phrase(['Kopat'], ['To Dig']),
  new Phrase(['Koshka'], ['Cat']),
  new Phrase(['Kot'], ['Tomcat']),
  new Phrase(['Krovvy'], ['Blood']),
  new Phrase(['Kupet'], ['To Buy']),
  new Phrase(['Lapa'], ['Paw']),
  new Phrase(['Lewdies'], ['People']),
  new Phrase(['Lighter'], ['Crone']),
  new Phrase(['Litso'], ['Face']),
  new Phrase(['Lomtick'], ['Slice']),
  new Phrase(['Loveted'], ['Caught']),
  new Phrase(['Lubbilubbing'], ['Making love']),
  new Phrase(['Luscious Glory'], ['Hair']),
  new Phrase(['Malchick'], ['Boy']),
  new Phrase(['Malenky'], ['Little']),
  new Phrase(['Maslo'], ['Butter']),
  new Phrase(['Merzky'], ['Filthy']),
  new Phrase(['Messel'], ['Thought']),
  new Phrase(['Mesto'], ['Place']),
  new Phrase(['Millicent'], ['Policeman']),
  new Phrase(['Minoota'], ['Minute']),
  new Phrase(['Molodoy'], ['Young']),
  new Phrase(['Moloko'], ['Milk']),
  new Phrase(['Moodge'], ['Man']),
  new Phrase(['Morder'], ['Snout']),
  new Phrase(['Mounch'], ['Snack']),
  new Phrase(['Mozg'], ['Brain']),
  new Phrase(['Nachinat'], ['To Begin']),
  new Phrase(['Nadmenny'], ['Arrogant']),
  new Phrase(['Nadsat'], ['Teenage']),
  new Phrase(['Nagoy'], ['Naked']),
  new Phrase(['Nazz'], ['Fool']),
  new Phrase(['Neezhnies'], ['Underpants']),
  new Phrase(['Nochy'], ['Night']),
  new Phrase(['Noga'], ['Foot']),
  new Phrase(['Nozh'], ['Knife']),
  new Phrase(['Nuking'], ['Smelling']),
  new Phrase(['Oddy-knocky'], ['Lonesome']),
  new Phrase(['Odin'], ['One']),
  new Phrase(['Okno'], ['Window']),
  new Phrase(['Oobivat'], ['To Kill']),
  new Phrase(['Ookadeet'], ['To leave']),
  new Phrase(['Ooko'], ['Ear']),
  new Phrase(['Oomny'], ['Clever']),
  new Phrase(['Oozhassny'], ['Terrible']),
  new Phrase(['Oozy'], ['Chain']),
  new Phrase(['Orange'], ['Man']),
  new Phrase(['Osoosh'], ['To Dry']),
  new Phrase(['Otchkies'], ['Eyeglasses']),
  new Phrase(['Pan-handle'], ['Erection']),
  new Phrase(['Pee'], ['Father']),
  new Phrase(['Peet'], ['To Drink']),
  new Phrase(['Pishcha'], ['Food']),
  new Phrase(['Platch'], ['To Cry']),
  new Phrase(['Platties'], ['Clothes']),
  new Phrase(['Plenny'], ['Prisoner']),
  new Phrase(['Plesk'], ['Splash']),
  new Phrase(['Pletcho'], ['Shoulder']),
  new Phrase(['Plott'], ['Flesh', 'body']),
  new Phrase(['Podooshka'], ['Pillow']),
  new Phrase(['Pol'], ['Sex']),
  new Phrase(['Polezny'], ['Useful']),
  new Phrase(['Polyclef'], ['Skeleton key']),
  new Phrase(['Pony'], ['To understand']),
  new Phrase(['Poogly'], ['Scared']),
  new Phrase(['Pooshka'], ['Gun']),
  new Phrase(['Pop-disk'], ['Pop-music disc']),
  new Phrase(['Prestoopnik'], ['Criminal']),
  new Phrase(['Pretty Polly'], ['Money']),
  new Phrase(['Privodeet'], ['To lead somewhere']),
  new Phrase(['Prod'], ['To produce']),
  new Phrase(['Ptitsa'], ['Girl']),
  new Phrase(['Pyahnitsa'], ['Drunk']),
  new Phrase(['Rabbit'], ['Work']),
  new Phrase(['Radosty'], ['Joy']),
  new Phrase(['Raskazz'], ['Story']),
  new Phrase(['Rasoodock'], ['Mind']),
  new Phrase(['Raz'], ['Time']),
  new Phrase(['Razdrez'], ['Upset']),
  new Phrase(['Razrez'], ['To Rip']),
  new Phrase(['Rooker'], ['Hand']),
  new Phrase(['Rot'], ['Mouth']),
  new Phrase(['Rozz'], ['Policeman']),
  new Phrase(['Sabog'], ['Shoe']),
  new Phrase(['Sakar'], ['Sugar']),
  new Phrase(['Sammy'], ['Generous']),
  new Phrase(['Sarky'], ['Sarcastic']),
  new Phrase(['Scoteena'], ['Cow']),
  new Phrase(['Shaika'], ['Gang']),
  new Phrase(['Sharp'], ['Female']),
  new Phrase(['Sharries'], ['Balls']),
  new Phrase(['Shest'], ['Pole']),
  new Phrase(['Shilarny'], ['Concern']),
  new Phrase(['Shive'], ['Slice', 'cut']),
  new Phrase(['Shiyah'], ['Neck']),
  new Phrase(['Shlaga'], ['Club']),
  new Phrase(['Shlapa'], ['Hat']),
  new Phrase(['Shlem'], ['Helmet']),
  new Phrase(['Shoom'], ['Noise']),
  new Phrase(['Shoot'], ['Fool']),
  new Phrase(['Sinny'], ['Movies', 'film']),
  new Phrase(['Skazat'], ['To say']),
  new Phrase(['Skolliwoll'], ['School']),
  new Phrase(['Skorry'], ['Quick', 'quickly']),
  new Phrase(['Skriking'], ['Scratching']),
  new Phrase(['Skvat'], ['To Grab']),
  new Phrase(['Sladky'], ['Sweet']),
  new Phrase(['Sloochat'], ['To happen']),
  new Phrase(['Slooshy'], ['To listen', 'hear']),
  new Phrase(['Slovo'], ['Word']),
  new Phrase(['Smeck'], ['Laugh']),
  new Phrase(['Smot'], ['To look']),
  new Phrase(['Sneety'], ['Dream']),
  new Phrase(['Snoutie'], ['Tobacco', 'snuff']),
  new Phrase(['Snuff It'], ['To Die']),
  new Phrase(['Sobirat'], ['To Pick Up']),
  new Phrase(['Sod'], ['Bastard']),
  new Phrase(['Sodding'], ['Fucking']),
  new Phrase(['Soomka'], ['Woman']),
  new Phrase(['Soviet'], ['Advice', 'order']),
  new Phrase(['Spat', 'spatchka'], ['Sleep']),
  new Phrase(['Spoogy'], ['Terrified']),
  new Phrase(['Staja'], ['State Jail']),
  new Phrase(['Starry'], ['Old', 'ancient']),
  new Phrase(['Strack'], ['Horror']),
  new Phrase(['Synthmesc'], ['A particular drug']),
  new Phrase(['Tally'], ['Waist']),
  new Phrase(['Tashtook'], ['Handkerchief']),
  new Phrase(['Tass'], ['Cup']),
  new Phrase(['Tolchock'], ['To hit']),
  new Phrase(['Toofles'], ['Slippers']),
  new Phrase(['Tree'], ['Three']),
  new Phrase(['Vareet'], ['To cook up']),
  new Phrase(['Vaysay'], ['Washroom', 'toilet']),
  new Phrase(['Veck'], ['Guy']),
  new Phrase(['Vellocet'], ['A particular drug']),
  new Phrase(['Veshch'], ['Thing']),
  new Phrase(['Viddy'], ['To see']),
  new Phrase(['Voloss'], ['Hair']),
  new Phrase(['Von'], ['Smell']),
  new Phrase(['Vred'], ['To Harm']),
  new Phrase(['Warble'], ['Song']),
  new Phrase(['Yahma'], ['Hole']),
  new Phrase(['Yahoody'], ['Jew']),
  new Phrase(['Yahzick'], ['Tongue']),
  new Phrase(['Yarbles'], ['Balls', 'testicles']),
  new Phrase(['Yeckate'], ['To Drive']),
  new Phrase(['Zammechat'], ['Remarkable']),
  new Phrase(['Zasnoot'], ['To Sleep']),
  new Phrase(['Zheena'], ['Wife']),
  new Phrase(['Zoobies'], ['Teeth']),
  new Phrase(['Zvonock'], ['Doorbell', 'Bellpull']),
  new Phrase(['Zvook'], ['Sound'])
];

